package com.infin.entity;

public enum RoleName {
    ROLE_PLATFORM_ADMIN,
    ROLE_PLATFORM_MANAGER,
    ROLE_PLATFORM_USER,
    ROLE_PROFESSIONAL_ADMIN,
    ROLE_PROFESSIONAL_MANAGER,
    ROLE_PROFESSIONAL_USER,
    CLIENT_ADMIN,
    CLIENT_USER,
    NOT_USER_ROLE
}
